import { test, expect } from '../support/fixtures';
import { signInAs } from '../support/fixtures';
import { E2E_USERS } from '../support/fake-server';

/**
 * Slice 13-UI-B — the machines journey (owner decision #3 / B-09; TEST_PLAN
 * E-06's "Administrator adds a machine" half): add a machine WITHOUT typing
 * a code → the backend-suggested provisional code renders RED (tone + icon
 * + the word PROVISIONAL — A-05, never colour alone) → the admin types the
 * real machine code → the flag clears and the code renders as any other.
 */

test('add machine → provisional RED → confirm real code → normal', async ({ page, server }) => {
  void server;
  await signInAs(page, E2E_USERS.admin.email);

  await page.getByRole('button', { name: 'Menu' }).click();
  await page.getByRole('button', { name: 'Administration' }).click();
  await page.getByRole('button', { name: /^Machines/ }).click();
  await expect(page.getByRole('heading', { name: 'Machines' })).toBeVisible();
  // Designed empty state, not a blank screen.
  await expect(page.getByText('No machines here yet.')).toBeVisible();

  await page.getByRole('button', { name: 'Add machine' }).click();
  await expect(page.getByRole('heading', { name: 'Add a machine' })).toBeVisible();
  await page.getByLabel('Asset type').selectOption({ label: 'Wire Bonder' });
  // Code deliberately left BLANK — the server suggests the provisional one.
  await page.getByRole('button', { name: 'Add machine' }).click();

  // Detail: the provisional code, unmistakably marked (A-05: icon + word +
  // tone, and the code shape itself is PROV-…, never a real plant code).
  const heading = page.getByRole('heading', { level: 1 });
  await expect(heading).toContainText(/^PROV-/);
  await expect(page.getByText('PROVISIONAL', { exact: true })).toBeVisible();
  await expect(page.getByText(/generated by the system/)).toBeVisible();

  // Review B-2: retyping the PROVISIONAL code itself is NOT a confirmation —
  // the server only clears the flag on an actual change, and the screen must
  // say so instead of printing a false "Code confirmed".
  const provisionalCode = (await heading.innerText()).trim();
  await page.getByLabel('Real machine code').fill(provisionalCode);
  await page.getByRole('button', { name: 'Confirm code' }).click();
  // (The provisional-explanation banner is also role=alert, so filter.)
  await expect(
    page.getByRole('alert').filter({ hasText: /IS the provisional code/ }),
  ).toBeVisible();
  await expect(page.getByText('PROVISIONAL', { exact: true })).toBeVisible();

  // Confirm by typing the real machine code.
  await page.getByLabel('Real machine code').fill('AW01');
  await page.getByRole('button', { name: 'Confirm code' }).click();
  await expect(page.getByText('Code confirmed as AW01.')).toBeVisible();
  await expect(heading).toHaveText('AW01');
  await expect(page.getByText('PROVISIONAL', { exact: true })).not.toBeVisible();

  // Back on the list: AW01 appears under its asset type, no red mark.
  await page.getByRole('button', { name: 'Machines', exact: true }).first().click();
  await expect(page.getByText('AW01')).toBeVisible();
  await expect(page.getByText('PROVISIONAL', { exact: true })).not.toBeVisible();

  // The per-asset-type dropdown genuinely filters: Aging Oven has none.
  await page.getByLabel('Asset type').selectOption({ label: 'Aging Oven' });
  await expect(page.getByText('No machines here yet.')).toBeVisible();
  await expect(page.getByText('AW01')).not.toBeVisible();
});

test('B-1: a machine can be moved into an area, OUT to "No area", and back — the clear is real', async ({
  page,
  server,
}) => {
  const bondLine = server.seedArea({ code: 'BL', name: 'Bond Line' });
  const testBay = server.seedArea({ code: 'TB', name: 'Test Bay' });
  await signInAs(page, E2E_USERS.admin.email);

  // Create IN Bond Line.
  await page.goto('/admin/machines/new');
  await page.getByLabel('Asset type').selectOption({ label: 'Wire Bonder' });
  await page.getByLabel('Machine code (optional)').fill('EP01');
  await page.getByLabel('Area (optional)').selectOption({ label: 'Bond Line (BL)' });
  await page.getByRole('button', { name: 'Add machine' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('EP01');
  const areaSelect = page.getByLabel('Area', { exact: true });
  await expect(areaSelect).toHaveValue(bondLine.id);

  // Move OUT: "No area" must genuinely clear the assignment (an explicit
  // null over the wire), not silently keep the old area.
  await areaSelect.selectOption({ label: 'No area' });
  await page.getByRole('button', { name: 'Save details' }).click();
  await expect(page.locator('.banner[data-tone="good"]')).toContainText('Saved.');
  await expect(areaSelect).toHaveValue('');

  // Reload from the server — the clear survived the round trip.
  await page.reload();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('EP01');
  await expect(page.getByLabel('Area', { exact: true })).toHaveValue('');

  // And back IN, to a different area.
  await page.getByLabel('Area', { exact: true }).selectOption({ label: 'Test Bay (TB)' });
  await page.getByRole('button', { name: 'Save details' }).click();
  await expect(page.locator('.banner[data-tone="good"]')).toContainText('Saved.');
  await expect(page.getByLabel('Area', { exact: true })).toHaveValue(testBay.id);
});

test('a duplicate machine code is refused by the server and surfaced honestly', async ({
  page,
  server,
}) => {
  void server;
  await signInAs(page, E2E_USERS.admin.email);
  await page.goto('/admin/machines/new');
  await page.getByLabel('Asset type').selectOption({ label: 'Wire Bonder' });
  await page.getByLabel('Machine code (optional)').fill('BD01');
  await page.getByRole('button', { name: 'Add machine' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('BD01');
  // A code the admin typed is treated as the real one — no provisional flag.
  await expect(page.getByText('PROVISIONAL', { exact: true })).not.toBeVisible();

  await page.goto('/admin/machines/new');
  await page.getByLabel('Asset type').selectOption({ label: 'Wire Bonder' });
  await page.getByLabel('Machine code (optional)').fill('BD01');
  await page.getByRole('button', { name: 'Add machine' }).click();
  await expect(page.getByRole('alert')).toContainText("Asset code 'BD01' is already in use.");
});
