import { test, expect } from '../support/fixtures';
import { signInAs } from '../support/fixtures';
import { E2E_USERS } from '../support/fake-server';

/**
 * Slice 13-UI-B — the machines journey (owner decision #3 / B-09; TEST_PLAN
 * E-06's "Administrator adds a machine" half): add a machine WITHOUT typing
 * a code → the backend-suggested provisional code renders RED (tone + icon
 * + the word PROVISIONAL — A-05, never colour alone) → the admin types the
 * real machine code → the flag clears and the code renders as any other.
 */

test('add machine → provisional RED → confirm real code → normal', async ({ page, server }) => {
  void server;
  await signInAs(page, E2E_USERS.admin.email);

  await page.getByRole('button', { name: 'Menu' }).click();
  await page.getByRole('button', { name: 'Administration' }).click();
  await page.getByRole('button', { name: /^Machines/ }).click();
  await expect(page.getByRole('heading', { name: 'Machines' })).toBeVisible();
  // Designed empty state, not a blank screen.
  await expect(page.getByText('No machines here yet.')).toBeVisible();

  await page.getByRole('button', { name: 'Add machine' }).click();
  await expect(page.getByRole('heading', { name: 'Add a machine' })).toBeVisible();
  await page.getByLabel('Asset type').selectOption({ label: 'Wire Bonder' });
  // Code deliberately left BLANK — the server suggests the provisional one.
  await page.getByRole('button', { name: 'Add machine' }).click();

  // Detail: the provisional code, unmistakably marked (A-05: icon + word +
  // tone, and the code shape itself is PROV-…, never a real plant code).
  const heading = page.getByRole('heading', { level: 1 });
  await expect(heading).toContainText(/^PROV-/);
  await expect(page.getByText('PROVISIONAL', { exact: true })).toBeVisible();
  await expect(page.getByText(/generated by the system/)).toBeVisible();

  // Confirm by typing the real machine code.
  await page.getByLabel('Real machine code').fill('AW01');
  await page.getByRole('button', { name: 'Confirm code' }).click();
  await expect(page.getByText('Code confirmed as AW01.')).toBeVisible();
  await expect(heading).toHaveText('AW01');
  await expect(page.getByText('PROVISIONAL', { exact: true })).not.toBeVisible();

  // Back on the list: AW01 appears under its asset type, no red mark.
  await page.getByRole('button', { name: 'Machines', exact: true }).first().click();
  await expect(page.getByText('AW01')).toBeVisible();
  await expect(page.getByText('PROVISIONAL', { exact: true })).not.toBeVisible();

  // The per-asset-type dropdown genuinely filters: Aging Oven has none.
  await page.getByLabel('Asset type').selectOption({ label: 'Aging Oven' });
  await expect(page.getByText('No machines here yet.')).toBeVisible();
  await expect(page.getByText('AW01')).not.toBeVisible();
});

test('a duplicate machine code is refused by the server and surfaced honestly', async ({
  page,
  server,
}) => {
  void server;
  await signInAs(page, E2E_USERS.admin.email);
  await page.goto('/admin/machines/new');
  await page.getByLabel('Asset type').selectOption({ label: 'Wire Bonder' });
  await page.getByLabel('Machine code (optional)').fill('BD01');
  await page.getByRole('button', { name: 'Add machine' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('BD01');
  // A code the admin typed is treated as the real one — no provisional flag.
  await expect(page.getByText('PROVISIONAL', { exact: true })).not.toBeVisible();

  await page.goto('/admin/machines/new');
  await page.getByLabel('Asset type').selectOption({ label: 'Wire Bonder' });
  await page.getByLabel('Machine code (optional)').fill('BD01');
  await page.getByRole('button', { name: 'Add machine' }).click();
  await expect(page.getByRole('alert')).toContainText("Asset code 'BD01' is already in use.");
});
