package com.bamform.shell

import android.net.Uri
import org.json.JSONObject

/**
 * `version.json` — the release manifest served next to the APK at
 * [MANIFEST_URL], and the model of what the shell will accept from it.
 *
 * ## This is a CODE-DELIVERY CHANNEL. Read the origin rule before changing it.
 *
 * [UPDATE_ORIGIN] is a **compile-time constant over HTTPS** and is
 * deliberately **NOT** `ServerConfig.get(context)`. The shell's *content*
 * origin is admin-configurable at runtime — that is the whole point of the
 * Server disclosure, and `network_security_config.xml` permits cleartext to
 * every destination so a plant LAN IP works. Deriving the update source from
 * that origin would mean: whoever controls the configured server (an admin, a
 * compromised plant host, or an on-path attacker on a cleartext LAN) also
 * chooses which APK the technician's device is invited to install. Serving
 * pages is a much smaller privilege than shipping code, and the two must not
 * be the same privilege.
 *
 * So the update channel is pinned to the origin that builds and signs the
 * binary, and that host is additionally pinned to **HTTPS-only** in
 * `network_security_config.xml`, so no stale preference or DNS answer can
 * downgrade it to cleartext. A shell pointed at a private plant server still
 * fetches its updates from `form.bevorasg.com`; that is intended, and stated
 * in `android/README.md`.
 *
 * ## Everything in this file treats the manifest as attacker-controlled
 *
 * TLS is the reason to believe the manifest is genuine, but it is not the
 * only defence. [parse] rejects anything it does not fully understand, and
 * [isTrustedUpdateUrl] re-derives the download target's origin from the
 * pinned constants rather than trusting the manifest's own idea of where the
 * APK lives — a forged manifest therefore cannot redirect the download
 * anywhere. Downstream, `UpdateService` re-checks the URL, verifies the
 * SHA-256 of the bytes on disk, and verifies that the archive is signed by
 * the same key as the running app before any installer sees it.
 *
 * ## Fields
 *
 * ```json
 * {
 *   "versionCode":  2,
 *   "versionName":  "1.2.0",
 *   "apkUrl":       "https://form.bevorasg.com/app/bamform-1.2.0.apk",
 *   "sha256":       "<64 lowercase hex chars, of the APK bytes>",
 *   "releaseNote":  "One short line shown in the update prompt.",
 *   "releasedAt":   "2026-07-28T12:00:00Z"
 * }
 * ```
 *
 * Generated by the Gradle task `:app:generateReleaseUpdateManifest`, which
 * reads the built APK. It is never hand-written: a manifest that drifts from
 * the binary either offers an update that does not exist or hides one that
 * does.
 */
data class UpdateManifest(
    val versionCode: Long,
    val versionName: String,
    val apkUrl: String,
    val sha256: String,
    val releaseNote: String,
    val releasedAt: String,
) {
    companion object {
        /**
         * PINNED. Compile-time, HTTPS, not runtime-configurable. See the
         * class KDoc for why this is not the configured content origin.
         */
        const val UPDATE_ORIGIN = "https://form.bevorasg.com"

        /** Host half of [UPDATE_ORIGIN], compared lower-cased. */
        const val UPDATE_HOST = "form.bevorasg.com"

        /** Every update artefact must live under this path on [UPDATE_ORIGIN]. */
        const val UPDATE_DIR = "/app/"

        /** The one URL the shell will read a manifest from. */
        const val MANIFEST_URL = "https://form.bevorasg.com/app/version.json"

        /** A manifest is a handful of short strings; anything larger is not one. */
        const val MAX_MANIFEST_BYTES = 8 * 1024

        private const val MAX_RELEASE_NOTE_CHARS = 240
        private const val MAX_RELEASED_AT_CHARS = 40

        private val SHA256_RE = Regex("^[0-9a-f]{64}$")
        private val VERSION_NAME_RE = Regex("^[A-Za-z0-9][A-Za-z0-9._+-]{0,31}$")
        private val CONTROL_RE = Regex("\\p{Cntrl}")

        /**
         * True only for a URL that is unambiguously an APK published by the
         * pinned update origin.
         *
         * The prefix test alone would be enough on a strict URL parser, but
         * the checks are layered on purpose: this predicate is the last line
         * between a manifest field and an outbound request, and Android's
         * [Uri] is lenient in places (backslashes, missing authority, embedded
         * credentials). Each clause is cheap and each closes a different way
         * of writing a URL that *looks* like it points at the update origin
         * and does not.
         */
        fun isTrustedUpdateUrl(raw: String): Boolean {
            if (raw.length > 512) return false
            // Authority-anchored prefix: pins scheme, host and directory in
            // one comparison, and forbids `https://form.bevorasg.com.evil.tld/app/`
            // (the dot after the host is part of the required prefix).
            if (!raw.startsWith(UPDATE_ORIGIN + UPDATE_DIR)) return false
            // No path traversal, no query, no fragment: the file is addressed
            // directly or not at all.
            if (raw.contains("..") || raw.contains('?') || raw.contains('#')) return false
            if (raw.contains('\\') || raw.contains('@')) return false
            val uri = Uri.parse(raw)
            if (uri.scheme != "https") return false
            if (uri.userInfo != null) return false
            if (uri.host?.lowercase() != UPDATE_HOST) return false
            if (uri.port != -1 && uri.port != 443) return false
            val path = uri.path ?: return false
            return path.startsWith(UPDATE_DIR) && path.endsWith(".apk")
        }

        /**
         * Strict parse. Returns null — never a partially-trusted object — for
         * anything that is not a complete, well-formed manifest. The caller
         * treats null as "no update", which is the correct degraded state:
         * the technician carries on using the app.
         */
        fun parse(text: String): UpdateManifest? {
            if (text.length > MAX_MANIFEST_BYTES) return null
            val json = try { JSONObject(text) } catch (_: Exception) { return null }

            val versionCode = json.optLong("versionCode", -1L)
            // Android's own versionCode is a 32-bit int; a manifest claiming
            // more is malformed, and clamping instead of refusing would let a
            // huge number masquerade as "newer than anything".
            if (versionCode <= 0L || versionCode > Int.MAX_VALUE.toLong()) return null

            val versionName = json.optString("versionName")
            if (!VERSION_NAME_RE.matches(versionName)) return null

            val apkUrl = json.optString("apkUrl")
            if (!isTrustedUpdateUrl(apkUrl)) return null

            val sha256 = json.optString("sha256").lowercase()
            if (!SHA256_RE.matches(sha256)) return null

            return UpdateManifest(
                versionCode = versionCode,
                versionName = versionName,
                apkUrl = apkUrl,
                sha256 = sha256,
                // Free text from the network, rendered in the app's own UI:
                // strip control characters (including newlines, which would
                // let a note push the buttons off-screen) and bound it.
                releaseNote = sanitize(json.optString("releaseNote"), MAX_RELEASE_NOTE_CHARS),
                releasedAt = sanitize(json.optString("releasedAt"), MAX_RELEASED_AT_CHARS),
            )
        }

        private fun sanitize(raw: String, max: Int): String =
            CONTROL_RE.replace(raw, " ").trim().take(max)
    }
}
