import { ConfigService } from '@nestjs/config';
import { computeEmailBlindIndex } from '../../../src/auth/crypto/blind-index';
import { encodeIdentityField } from '../../../src/auth/crypto/identity-codec';
import { PasswordService } from '../../../src/auth/password/password.service';
import { SecretFileLoader } from '../../../src/secret-loading/secret-loader';
import { adminPool } from './db';

/**
 * Loads the SAME blind-index key the running application resolves via
 * `SecretFileLoader` (falls back to the git-ignored `secrets/blind_index_key`
 * generated by `scripts/dev/generate-dev-secrets.sh`), so a fixture-seeded
 * user's `email_bidx` matches what `AuthService.login` computes at request
 * time.
 */
function loadBlindIndexKey(): Buffer {
  const raw = new SecretFileLoader().load('blind_index_key').toString('utf8').trim();
  return Buffer.from(raw, 'base64');
}

const passwordService = new PasswordService(new ConfigService({}));

export interface LoginableUserOpts {
  email: string;
  password: string;
  fullName?: string;
  roleCodes?: string[];
}

/**
 * Seeds a real, loginable `app_user` row (password hashed with the actual
 * `PasswordService`/Argon2id, real HMAC blind index) — bypassing the API
 * (there is no user-creation endpoint yet; that's a later slice), the same
 * way slice 1's `fixtures.ts#createUser` seeds rows directly for its
 * integration suite.
 */
export async function createLoginableUser(opts: LoginableUserOpts): Promise<{ userId: string }> {
  const passwordHash = await passwordService.hash(opts.password);
  const bidx = computeEmailBlindIndex(opts.email, loadBlindIndexKey());

  const result = await adminPool.query(
    `INSERT INTO "app_user" ("full_name_ct", "email_ct", "email_bidx", "password_hash", "dek_version")
     VALUES ($1, $2, $3, $4, 1)
     RETURNING id`,
    [
      encodeIdentityField(opts.fullName ?? 'Test User'),
      encodeIdentityField(opts.email),
      bidx,
      passwordHash,
    ],
  );
  const userId = result.rows[0].id as string;

  for (const code of opts.roleCodes ?? []) {
    await adminPool.query(
      `INSERT INTO "user_role" ("user_id", "role_id", "granted_by")
       SELECT $1, "id", $1 FROM "role" WHERE "code" = $2`,
      [userId, code],
    );
  }

  return { userId };
}
