import { ConfigService } from '@nestjs/config';
import { v7 as uuidv7 } from 'uuid';
import {
  computeEmailBlindIndex,
  computeRecoveryCodeBlindIndex,
} from '../../../src/auth/crypto/blind-index';
import { encodeIdentityField } from '../../../src/auth/crypto/identity-codec';
import { base32Encode } from '../../../src/auth/mfa/base32';
import { PasswordService } from '../../../src/auth/password/password.service';
import { buildFieldEncryptionService } from '../../../src/crypto/crypto-bootstrap';
import type { FieldEncryptionService } from '../../../src/crypto/field-encryption';
import { SecretFileLoader } from '../../../src/secret-loading/secret-loader';
import { adminPool } from './db';

/**
 * Loads the SAME key material the running application resolves via
 * `SecretFileLoader`/`CryptoModule` (falls back to the git-ignored `secrets/`
 * generated by `scripts/dev/generate-dev-secrets.sh`), so a fixture-seeded user's
 * `email_bidx` and encrypted columns match what `AuthService` computes at request
 * time.
 */
export function loadBlindIndexKey(): Buffer {
  const raw = new SecretFileLoader().load('blind_index_key').toString('utf8').trim();
  return Buffer.from(raw, 'base64');
}

export function loadFieldEncryptionService(): FieldEncryptionService {
  const loader = new SecretFileLoader();
  const kek = Buffer.from(loader.load('kek').toString('utf8').trim(), 'base64');
  const wrappedDek = Buffer.from(loader.load('dek_wrapped').toString('utf8').trim(), 'base64');
  return buildFieldEncryptionService({
    kek,
    wrappedDek,
    currentDekVersion: Number(process.env.DEK_VERSION ?? 1),
    blindIndexKey: loadBlindIndexKey(),
  });
}

const passwordService = new PasswordService(new ConfigService({}));

export interface LoginableUserOpts {
  email: string;
  password: string;
  fullName?: string;
  roleCodes?: string[];
}

/**
 * Seeds a real, loginable `app_user` row — password hashed with the actual
 * `PasswordService`/Argon2id, real HMAC blind index, real AES-256-GCM field
 * encryption (PR-106/107) — bypassing the API (there is no user-creation endpoint
 * yet; that's a later slice), the same way slice 1's `fixtures.ts#createUser` seeds
 * rows directly for its integration suite.
 *
 * The row id is generated client-side as a UUIDv7 (SECURITY_ARCHITECTURE.md §8
 * crypto inventory: "Identifiers | UUIDv7 | — | Time-ordered; client-generatable
 * offline") rather than left to the schema's `dbgenerated("uuidv7()")` default,
 * because the AAD binding the ciphertext to its row (PR-106) requires the row id to
 * be known BEFORE encryption happens, i.e. before the INSERT.
 */
export async function createLoginableUser(opts: LoginableUserOpts): Promise<{ userId: string }> {
  const passwordHash = await passwordService.hash(opts.password);
  const bidx = computeEmailBlindIndex(opts.email, loadBlindIndexKey());
  const fieldEncryption = loadFieldEncryptionService();

  const userId = uuidv7();
  const fullName = encodeIdentityField(
    opts.fullName ?? 'Test User',
    { column: 'full_name_ct', rowId: userId },
    fieldEncryption,
  );
  const email = encodeIdentityField(
    opts.email,
    { column: 'email_ct', rowId: userId },
    fieldEncryption,
  );

  const result = await adminPool.query(
    `INSERT INTO "app_user"
       ("id", "full_name_ct", "email_ct", "email_bidx", "password_hash", "dek_version")
     VALUES ($1, $2, $3, $4, $5, $6)
     RETURNING id`,
    [userId, fullName.ciphertext, email.ciphertext, bidx, passwordHash, fullName.dekVersion],
  );
  const insertedUserId = result.rows[0].id as string;

  for (const code of opts.roleCodes ?? []) {
    await adminPool.query(
      `INSERT INTO "user_role" ("user_id", "role_id", "granted_by")
       SELECT $1, "id", $1 FROM "role" WHERE "code" = $2`,
      [insertedUserId, code],
    );
  }

  return { userId: insertedUserId };
}

/**
 * Slice 13-MFA — seeds a completed TOTP enrolment directly, so a test can
 * drive `/auth/mfa/verify` with a code it can compute itself. Uses the REAL
 * field-encryption path (same AAD binding `MfaService` uses), not a stub, so
 * a mismatch between fixture and service would fail loudly rather than
 * quietly passing.
 */
export async function enrolMfaForUser(userId: string, secret: Buffer): Promise<void> {
  const fieldEncryption = loadFieldEncryptionService();
  const encrypted = fieldEncryption.encrypt(base32Encode(secret), {
    table: 'app_user',
    column: 'mfa_secret_ct',
    rowId: userId,
  });
  await adminPool.query(
    `UPDATE "app_user"
        SET "mfa_enrolled" = true,
            "mfa_secret_ct" = $2,
            "mfa_secret_dek_version" = $3,
            "mfa_enrolled_at" = now(),
            "mfa_last_used_step" = NULL
      WHERE "id" = $1`,
    [userId, encrypted.ciphertext, encrypted.dekVersion],
  );
}

/** Seeds recovery codes for a user the way `MfaService.confirmEnrolment` does. */
export async function seedRecoveryCodes(userId: string, codes: readonly string[]): Promise<void> {
  const key = loadBlindIndexKey();
  for (const code of codes) {
    await adminPool.query(
      `INSERT INTO "mfa_recovery_code" ("user_id", "code_bidx") VALUES ($1, $2)`,
      [userId, computeRecoveryCodeBlindIndex(code, key)],
    );
  }
}

/** Slice 13-MFA §7 — puts an existing user behind the forced-password-change gate. */
export async function setMustChangePassword(userId: string, value: boolean): Promise<void> {
  await adminPool.query(`UPDATE "app_user" SET "must_change_password" = $2 WHERE "id" = $1`, [
    userId,
    value,
  ]);
}
