import { ConfigService } from '@nestjs/config';
import { v7 as uuidv7 } from 'uuid';
import { computeEmailBlindIndex } from '../../../src/auth/crypto/blind-index';
import { encodeIdentityField } from '../../../src/auth/crypto/identity-codec';
import { PasswordService } from '../../../src/auth/password/password.service';
import { buildFieldEncryptionService } from '../../../src/crypto/crypto-bootstrap';
import type { FieldEncryptionService } from '../../../src/crypto/field-encryption';
import { SecretFileLoader } from '../../../src/secret-loading/secret-loader';
import { adminPool } from './db';

/**
 * Loads the SAME key material the running application resolves via
 * `SecretFileLoader`/`CryptoModule` (falls back to the git-ignored `secrets/`
 * generated by `scripts/dev/generate-dev-secrets.sh`), so a fixture-seeded user's
 * `email_bidx` and encrypted columns match what `AuthService` computes at request
 * time.
 */
export function loadBlindIndexKey(): Buffer {
  const raw = new SecretFileLoader().load('blind_index_key').toString('utf8').trim();
  return Buffer.from(raw, 'base64');
}

export function loadFieldEncryptionService(): FieldEncryptionService {
  const loader = new SecretFileLoader();
  const kek = Buffer.from(loader.load('kek').toString('utf8').trim(), 'base64');
  const wrappedDek = Buffer.from(loader.load('dek_wrapped').toString('utf8').trim(), 'base64');
  return buildFieldEncryptionService({
    kek,
    wrappedDek,
    currentDekVersion: Number(process.env.DEK_VERSION ?? 1),
    blindIndexKey: loadBlindIndexKey(),
  });
}

const passwordService = new PasswordService(new ConfigService({}));

export interface LoginableUserOpts {
  email: string;
  password: string;
  fullName?: string;
  roleCodes?: string[];
}

/**
 * Seeds a real, loginable `app_user` row — password hashed with the actual
 * `PasswordService`/Argon2id, real HMAC blind index, real AES-256-GCM field
 * encryption (PR-106/107) — bypassing the API (there is no user-creation endpoint
 * yet; that's a later slice), the same way slice 1's `fixtures.ts#createUser` seeds
 * rows directly for its integration suite.
 *
 * The row id is generated client-side as a UUIDv7 (SECURITY_ARCHITECTURE.md §8
 * crypto inventory: "Identifiers | UUIDv7 | — | Time-ordered; client-generatable
 * offline") rather than left to the schema's `dbgenerated("uuidv7()")` default,
 * because the AAD binding the ciphertext to its row (PR-106) requires the row id to
 * be known BEFORE encryption happens, i.e. before the INSERT.
 */
export async function createLoginableUser(opts: LoginableUserOpts): Promise<{ userId: string }> {
  const passwordHash = await passwordService.hash(opts.password);
  const bidx = computeEmailBlindIndex(opts.email, loadBlindIndexKey());
  const fieldEncryption = loadFieldEncryptionService();

  const userId = uuidv7();
  const fullName = encodeIdentityField(
    opts.fullName ?? 'Test User',
    { column: 'full_name_ct', rowId: userId },
    fieldEncryption,
  );
  const email = encodeIdentityField(
    opts.email,
    { column: 'email_ct', rowId: userId },
    fieldEncryption,
  );

  const result = await adminPool.query(
    `INSERT INTO "app_user"
       ("id", "full_name_ct", "email_ct", "email_bidx", "password_hash", "dek_version")
     VALUES ($1, $2, $3, $4, $5, $6)
     RETURNING id`,
    [userId, fullName.ciphertext, email.ciphertext, bidx, passwordHash, fullName.dekVersion],
  );
  const insertedUserId = result.rows[0].id as string;

  for (const code of opts.roleCodes ?? []) {
    await adminPool.query(
      `INSERT INTO "user_role" ("user_id", "role_id", "granted_by")
       SELECT $1, "id", $1 FROM "role" WHERE "code" = $2`,
      [insertedUserId, code],
    );
  }

  return { userId: insertedUserId };
}
