// scripts/template-load/src/masterlist/evidence.ts
/**
 * Slice masterlist-migration — Task 6: the evidence file.
 *
 * This is the artefact the owner actually diffs against the paper masterlist
 * (`ML-S-MFT-00015 Rev 21`) BEFORE anyone runs `--apply` — the CLI (`cli.ts`)
 * prints a reminder to do exactly that. Rendered purely from an
 * `ImportReport` (Task 4) plus the template catalogue the CLI assembled from
 * the committed YAML, so this module never touches the filesystem or the
 * network itself, and it renders identically for a dry run or a completed
 * apply — `MachineImportResult.dueDates` holds the same computed values
 * either way (see `import.ts`'s `processMapped`).
 *
 * One row per machine, in the masterlist's own order, keyed by the SOURCE
 * LABEL (`MasterlistRow.label` — verbatim column A) rather than just the
 * code, because that is the text a reviewer holding the spreadsheet actually
 * matches against.
 */
import type { ImportReport, ImportTemplateRef, MachineImportResult } from './import';

const FREQ_ORDER = ['M1', 'M3', 'M6', 'Y'];
const sortFreq = (a: string, b: string): number => FREQ_ORDER.indexOf(a) - FREQ_ORDER.indexOf(b);

function dueDatesCell(m: MachineImportResult): string {
  const entries = Object.entries(m.dueDates).sort(([a], [b]) => sortFreq(a, b));
  if (entries.length === 0) return '·';
  return entries.map(([freq, date]) => `${freq}: ${date}`).join('; ');
}

function documentFor(m: MachineImportResult, templates: Record<string, ImportTemplateRef>): string {
  if (!m.assetTypeCode) return '·';
  return templates[m.assetTypeCode]?.documentNumber ?? '·';
}

export interface EvidenceMeta {
  /** Path to the masterlist workbook this run read (`--file`, echoed verbatim). */
  file: string;
  /** Plan year (`--year`). */
  year: number;
  /** `assetTypeCode` -> its PM document, same catalogue the CLI passed to `runImport`. */
  templates: Record<string, ImportTemplateRef>;
}

export function renderImportEvidence(report: ImportReport, meta: EvidenceMeta): string {
  const { templates, file, year } = meta;
  const lines: string[] = [];
  const push = (...l: string[]) => lines.push(...l);

  const imported = report.machines.filter((m) => m.status === 'imported' && !m.leftUnplanned);
  const leftUnplanned = report.machines.filter((m) => m.leftUnplanned);
  const skipped = report.machines.filter((m) => m.status === 'skipped');
  const blocked = report.machines.filter(
    (m) => m.status === 'unmapped' || m.status === 'hard-error',
  );

  push(
    '# Masterlist Import Evidence — ML-S-MFT-00015 Rev 21',
    '',
    '**Diff this file against the paper masterlist before anyone runs `--apply`.** It is ' +
      'regenerated by every run of `npm run import:masterlist` — dry run or apply — from the ' +
      'exact reconciliation the importer itself acted on, so what is listed here is exactly ' +
      'what was (or would be) created. A dry run makes zero network calls, so producing this ' +
      'file is always safe.',
    '',
    '| | |',
    '|---|---|',
    `| Source workbook | \`${file}\` |`,
    `| Plan year | ${year} |`,
    `| Mode | ${report.dryRun ? 'DRY RUN — no writes were made' : 'APPLY — writes were performed'} |`,
    `| Generated | ${new Date().toISOString()} |`,
    '',
    '## Summary',
    '',
    '| | Count |',
    '|---|---|',
    `| Imported — machine + document created/reused, schedule planned | ${imported.length} |`,
    `| Left unplanned — machine + document only, schedule deliberately blank | ${leftUnplanned.length} |`,
    `| Skipped — owner decision (machine not on site) | ${skipped.length} |`,
    `| Unmapped / hard-error — blocked, needs an owner decision | ${blocked.length} |`,
    `| **Total rows in the masterlist** | **${report.machines.length}** |`,
    '',
  );

  // ---- Imported, with a schedule ---------------------------------------------
  push(
    `## Machines imported with a schedule — ${imported.length}`,
    '',
    'One row per machine, in the order the masterlist lists them. `Frequencies` is the FIRST ' +
      `planned due date the importer set for each frequency in ${year}; the interval carries ` +
      'each one forward from there. Cross-check every row against the same row of the ' +
      'spreadsheet before `--apply`.',
    '',
    '| Source label (masterlist column A) | Code | Asset type | Document | Frequencies (first due date) |',
    '|---|---|---|---|---|',
  );
  for (const m of imported) {
    push(
      `| ${m.label} | ${m.code} | ${m.assetTypeCode ?? '·'} | ${documentFor(m, templates)} | ${dueDatesCell(m)} |`,
    );
  }
  push('');

  // ---- Left unplanned ----------------------------------------------------------
  push(
    `## Left unplanned for a planner — ${leftUnplanned.length}`,
    '',
    'Owner decision 2026-08-03: when the PM document defines a frequency the plan does not ' +
      'schedule for this machine (a "surplus"), the machine and its document are still ' +
      'created, but the schedule is deliberately left BLANK — the importer never calls ' +
      '`GET /assets/{id}/schedule` for these rows, so no `schedule_rule` rows exist yet. They ' +
      'show up in the planner as unplanned; a human decides the actual dates from there. This ' +
      'is intentional, not a gap or a failure.',
    '',
    '| Source label | Code | Asset type | Document | Surplus frequency (form defines it, plan does not schedule it) |',
    '|---|---|---|---|---|',
  );
  for (const m of leftUnplanned) {
    push(
      `| ${m.label} | ${m.code} | ${m.assetTypeCode ?? '·'} | ${documentFor(m, templates)} | ${
        m.surplus.join(', ') || '·'
      } |`,
    );
  }
  push('');

  // ---- Skipped -------------------------------------------------------------------
  push(
    `## Skipped — ${skipped.length}`,
    '',
    'Deliberately not imported, by owner decision — the machine is not on site.',
    '',
    '| Source label | Reason |',
    '|---|---|',
  );
  for (const m of skipped) {
    push(
      `| ${m.label} | ${m.message ?? 'SKIPPED_LABELS — owner decision (machine not on site)'} |`,
    );
  }
  push('');

  // ---- Unmapped / hard-error ------------------------------------------------------
  push(`## Unmapped / hard-error — ${blocked.length}`, '');
  if (blocked.length === 0) {
    push('None. Every row above was either imported, left unplanned, or deliberately skipped.', '');
  } else {
    push(
      '**These rows were NOT imported and need an owner decision before this migration can be ' +
        'considered complete.**',
      '',
      '| Source label | Code | Status | Reason |',
      '|---|---|---|---|',
    );
    for (const m of blocked) {
      push(`| ${m.label} | ${m.code} | ${m.status} | ${m.message ?? '·'} |`);
    }
    push('');
  }

  return lines.join('\n');
}
